"""Add scripts table and call relation

Revision ID: 4915811db136
Revises: f1a2b3c4d5e6
Create Date: 2026-01-25 07:22:42.299557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4915811db136'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_external_id'), 'scripts', ['external_id'], unique=False)
    op.create_index(op.f('ix_scripts_id'), 'scripts', ['id'], unique=False)
    op.add_column('calls', sa.Column('script_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calls', 'scripts', ['script_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_column('calls', 'script_id')
    op.drop_index(op.f('ix_scripts_id'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_external_id'), table_name='scripts')
    op.drop_table('scripts')
    # ### end Alembic commands ###
