"""update_calls_table

Revision ID: 8c35ce8a5043
Revises: 9c561692c9d0
Create Date: 2026-01-24 13:03:22.041453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c35ce8a5043'
down_revision: Union[str, Sequence[str], None] = '9c561692c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'status')
    op.drop_column('calls', 'topic')
    # ### end Alembic commands ###
