"""add_notes_to_calls_nullable_answer

Revision ID: f478cca80a05
Revises: 4915811db136
Create Date: 2026-01-27 15:23:24.214694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f478cca80a05'
down_revision: Union[str, Sequence[str], None] = '4915811db136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scripts', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scripts', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
